<?php
/**
 * @file
 * Drupal hook implementations.
 */

/**
 * Custom drupal_http_request() wrapper that implements caching.
 *
 * @see drupal_http_request()
 */
function http_request_cache_http_request($url, array $options = array()) {

  // Create a cache key that is unique to this request. We hash it to prevent
  // any potentially sensitive information from being stored in the database.
  $args = func_get_args();
  $key = __FUNCTION__ . serialize($args);
  $cid = hash('sha512', drupal_get_hash_salt() . $key);

  // Skip POST requests no matter what.
  // All other requests get cached by default.
  $is_cacheable = empty($options['method']) || drupal_strtoupper($options['method']) != 'POST';

  // Allow modules to adjust cacheable status.
  if ($is_cacheable) {

    $context = array(
      'url' => $url,
      'options' => $options,
    );
    drupal_alter('http_request_is_cacheable', $is_cacheable, $context);
  }

  $result = NULL;

  if ($is_cacheable) {

    $result = &drupal_static($cid);
    // See if we have a static cached result so we can avoid the db completely.
    if (!empty($result)) {

      return $result;
    }
    // Check for a cached version of this request in the db.
    elseif($cache = cache_get($cid, 'cache_page')) {

      // Assign to our static cache before returning result.
      $result = $cache->data;
      return $result;
    }
  }

  // We need to remove our drupal_http_request() override so it doesn't result
  // in an infinite recursion scenario. We then need to restore our custom
  // setting after the call is complete.
  global $conf;
  $original_function = $conf['drupal_http_request_function'];
  $conf['drupal_http_request_function'] = FALSE;
  $result = call_user_func_array('drupal_http_request', $args);
  $conf['drupal_http_request_function'] = $original_function;

  if ($is_cacheable) {

    // Be sure to save this request so we can avoid it in the future.
    cache_set($cid, $result, 'cache_page');
  }

  return $result;
}

/**
 * Implements hook_boot().
 */
function http_request_cache_boot() {

  // Use our custom function only after the module is loaded. If this gets
  // defined by variable_set(), drush, or in settings.php it will cause the
  // site to break because the module hasn't been loaded before the function
  // is used.
  global $conf;
  $conf['drupal_http_request_function'] = 'http_request_cache_http_request';
}
